In [2]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

In [3]:
df = pd.read_csv("insurance_data.csv")
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

# Sample 1 

In this we will train our model using keras pre made neural network techniques 

In [5]:
from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(df[['age','affordibility']],df.bought_insurance,train_size= 0.8,random_state = 9)


In [6]:
x_train.head()

age  affordibility
18   19              0
19   18              1
6    55              0
2    47              1
12   27              0

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation = 'sigmoid' , kernel_initializer='ones', bias_initializer='zeros')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5000)

Epoch 1/5000


C:\Users\Z30\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 750ms/step - accuracy: 0.4091 - loss: 16.5455
Epoch 2/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.4091 - loss: 16.5283
Epoch 3/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.4091 - loss: 16.5112
Epoch 4/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.4091 - loss: 16.4940
Epoch 5/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.4091 - loss: 16.4769
Epoch 6/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.4091 - loss: 16.4598
Epoch 7/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.4091 - loss: 16.4426
Epoch 8/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.4091 - loss: 16.4255
Epoch 9/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.4091 - loss: 16.4084
Epoch 10/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.4091 - loss: 16.3912
Epoch 11/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.4091 - loss: 16.3741
Epoch 12/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 190ms/step - accuracy:

 ## Summary

 If we look after 1000 epochs we only get around 68% accuracy , so what can we do to improve this ?
 
Epoch 1000/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.6818 - loss: 0.6064

# Sample 2 

In this sample we will normalize our data so that we can get better results
we will normalize by dividing age by 100 , since age is not greater than 100 , this we will convert all the values in range of 0 to 1

In [15]:
x_train_scaled = x_train.copy()
x_train_scaled['age'] = x_train_scaled['age']/100

x_test_scaled = x_test.copy()
x_test_scaled['age'] = x_test_scaled['age']/100

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation = 'sigmoid' , kernel_initializer='ones', bias_initializer='zeros')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(x_train_scaled, y_train, epochs=5000)

C:\Users\Z30\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 815ms/step - accuracy: 0.4091 - loss: 0.8113
Epoch 2/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.4091 - loss: 0.8107
Epoch 3/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.4091 - loss: 0.8102
Epoch 4/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.4091 - loss: 0.8096
Epoch 5/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.4091 - loss: 0.8090
Epoch 6/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.4091 - loss: 0.8084
Epoch 7/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - accuracy: 0.4091 - loss: 0.8079
Epoch 8/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.4091 - loss: 0.8073
Epoch 9/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.4091 - loss: 0.8067
Epoch 10/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - accuracy: 0.4091 - loss: 0.8062
Epoch 11/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.4091 - loss: 0.8056
Epoch 12/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accura

 ## Summary

 So after normalization with the same code we get around 81% accuracy , so that shows how much important it is to normalize your data
 
Epoch 1000/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.8182 - loss: 0.6172

# Sample 3
In this sample we are going to use the weights generated by the previous model and create our own predicion fuction and test if it works or not

In [18]:
model.evaluate(x_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 243ms/step - accuracy: 0.8333 - loss: 0.4504


[0.4504106938838959, 0.8333333134651184]

In [19]:
model.predict(x_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step


array([[0.7118846 ],
       [0.7552008 ],
       [0.70269346],
       [0.61315036],
       [0.38115427],
       [0.46767837]], dtype=float32)

In [20]:
y_test

5     1
9     1
15    1
4     1
3     0
7     1
Name: bought_insurance, dtype: int64

In [22]:
coef, intercept = model.get_weights()
coef, intercept

(array([[4.4398084],
        [1.2116143]], dtype=float32),
 array([-2.7933521], dtype=float32))

In [23]:
def sigmoid(x):
    import math
    return 1/(1+math.exp(-x))

In [24]:
x_test_scaled

age  affordibility
5   0.56              1
9   0.61              1
15  0.55              1
4   0.46              1
3   0.52              0
7   0.60              0

In [25]:
def predictionFunction(age,afford):
    weighted_sum = age*coef[0] + afford*coef[1] + intercept
    return sigmoid(weighted_sum)

In [27]:
print(predictionFunction(0.56,1))
print(predictionFunction(0.55,1))
print(predictionFunction(0.52,0))


0.7118846243259083
0.7026934578037607
0.3811542727802474


C:\Users\Z30\AppData\Local\Temp\ipykernel_4864\1356804808.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1/(1+math.exp(-x))


# Sample 3 
In this sample we will create a neural network from complete basic including ,
* sigmoid function
* log_loss fuction (binary_crossentropy)
* gradient descent
* forward propogation
* backward propogation
* weights update

In [28]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [53]:
def log_loss(y_true,y_pred):
    epsilon = 1e-15
    y_predicted = [max(i,epsilon) for i in y_pred]
    y_predicted = [min(i,1-epsilon) for i in y_predicted]
    y_predicted = np.array(y_predicted)

    return -np.mean(y_true*np.log(y_predicted) + (1-y_train)*np.log(1-y_predicted))

In [54]:
def gradient_descent(age, affordability, y_true, epochs, loss_thresold):
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)

    for i in range(epochs):
        weighted_sum = age*w1 + affordability*w2 + bias
        y_pred = sigmoid(weighted_sum)
        loss = log_loss(y_true,y_pred)

        dw1 = (1/n)*np.dot(np.transpose(age),(y_pred-y_true))
        dw2 = (1/n)*np.dot(np.transpose(affordability),(y_pred-y_true))
        dbias = np.mean(y_pred-y_true)

        w1 = w1 - dw1*rate
        w2 = w2 - dw2*rate
        bias = bias - dbias*rate

        print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')

        if loss<=loss_thresold:
            break

    return w1, w2, bias
    

In [56]:
gradient_descent(x_train_scaled['age'],x_train_scaled['affordibility'],y_train,1000, 0.4631)

Epoch:0, w1:0.9637185148305161, w2:0.9093996372309792, bias:-0.15899971596505466, loss:0.8112923393691266
Epoch:1, w1:0.9352544224059377, w2:0.8342763027964821, bias:-0.29587120076432044, loss:0.7467829364894549
Epoch:2, w1:0.9141272528875863, w2:0.7739665146317435, bias:-0.41217449851311583, loss:0.7004872891780484
Epoch:3, w1:0.8995493866286928, w2:0.7270367334404036, bias:-0.5102466278941071, loss:0.6683042124878893
Epoch:4, w1:0.8905950174198587, w2:0.6916653859083445, bias:-0.5927373940392777, loss:0.6463777866260911
Epoch:5, w1:0.8863358567648945, w2:0.665962026575046, bias:-0.6622513545917619, loss:0.6315549163989057
Epoch:6, w1:0.8859227157417765, w2:0.6481660878096478, bias:-0.721141382418129, loss:0.6214890763931213
Epoch:7, w1:0.8886209236324227, w2:0.6367391082102101, bias:-0.7714258373860241, loss:0.6145400082112614
Epoch:8, w1:0.8938163375152498, w2:0.6303875959981848, bias:-0.8147819217528913, loss:0.6096067082582581
Epoch:9, w1:0.9010062743391487, w2:0.6280493660421587,

(np.float64(4.368218062183725),
 np.float64(1.4103107282472382),
 np.float64(-2.9587440933614184))

In [49]:
coef, intercept

(array([[4.4398084],
        [1.2116143]], dtype=float32),
 array([-2.7933521], dtype=float32))

# Creating Your own Neural Network Class

In [65]:
class myNN:
    def __init__(self):
        self.w1=1
        self.w2=1
        self.bias=0

    def fit (self , X , Y , epochs , loss_thresold):
        self.w1,self.w2,self.bias = self.gradient_descent(X['age'],X['affordibility'],Y,epochs,loss_thresold)

    def predict(self,X):
        weighted_sum = X['age']*self.w1 + X['affordibility']*self.w2 + self.bias
        return sigmoid(weighted_sum)

    def gradient_descent(self , age, affordability, y_true, epochs, loss_thresold):
        w1 = w2 = 1
        bias = 0
        rate = 0.5
        n = len(age)
    
        for i in range(epochs):
            weighted_sum = age*w1 + affordability*w2 + bias
            y_pred = sigmoid(weighted_sum)
            loss = log_loss(y_true,y_pred)
    
            dw1 = (1/n)*np.dot(np.transpose(age),(y_pred-y_true))
            dw2 = (1/n)*np.dot(np.transpose(affordability),(y_pred-y_true))
            dbias = np.mean(y_pred-y_true)
    
            w1 = w1 - dw1*rate
            w2 = w2 - dw2*rate
            bias = bias - dbias*rate
    
            print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
    
            if loss<=loss_thresold:
                break
    
        return w1, w2, bias
    

In [66]:
customModel = myNN()
customModel.fit(x_train_scaled, y_train, epochs=8000, loss_thresold=0.4631)

Epoch:0, w1:0.9637185148305161, w2:0.9093996372309792, bias:-0.15899971596505466, loss:0.8112923393691266
Epoch:1, w1:0.9352544224059377, w2:0.8342763027964821, bias:-0.29587120076432044, loss:0.7467829364894549
Epoch:2, w1:0.9141272528875863, w2:0.7739665146317435, bias:-0.41217449851311583, loss:0.7004872891780484
Epoch:3, w1:0.8995493866286928, w2:0.7270367334404036, bias:-0.5102466278941071, loss:0.6683042124878893
Epoch:4, w1:0.8905950174198587, w2:0.6916653859083445, bias:-0.5927373940392777, loss:0.6463777866260911
Epoch:5, w1:0.8863358567648945, w2:0.665962026575046, bias:-0.6622513545917619, loss:0.6315549163989057
Epoch:6, w1:0.8859227157417765, w2:0.6481660878096478, bias:-0.721141382418129, loss:0.6214890763931213
Epoch:7, w1:0.8886209236324227, w2:0.6367391082102101, bias:-0.7714258373860241, loss:0.6145400082112614
Epoch:8, w1:0.8938163375152498, w2:0.6303875959981848, bias:-0.8147819217528913, loss:0.6096067082582581
Epoch:9, w1:0.9010062743391487, w2:0.6280493660421587,

In [67]:
customModel.predict(x_test_scaled)

5     0.710491
9     0.753279
15    0.701424
4     0.613239
3     0.334640
7     0.416341
dtype: float64

In [69]:
model.predict(x_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step


array([[0.7118846 ],
       [0.7552008 ],
       [0.70269346],
       [0.61315036],
       [0.38115427],
       [0.46767837]], dtype=float32)

**Above you can compare predictions from our custom model and tensoflow model. You will notice that predictions are almost same**